### ISSUE TITLE
Revisar NullPointerException em org/organ_gerenciar_inscricoes.jsp

### ISSUE THREAD

**Issue by MateusPinheiro** [petufc/SEven#106]
Verificar o motivo do NullPointerException na pagina org/organ_gerenciar_inscricoes.jsp quando é utilizado o banco de dados de teste do @Max-Wendel-UFC

**Comment by Max-Wendel-UFC** [comment]
> Verificar o motivo do NullPointerException na pagina org/organ_gerenciar_inscricoes.jsp quando é utilizado o banco de dados de teste do @Max-Wendel-UFC

Isso tá acontecendo porque o script que o @lucivanbatista me passou acabou criando usuários com campos nulos. Vou rodar um _update_ no banco, pra tira-los.
